# Generated by Django 4.0.5 on 2022-06-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlasmak', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='DayNumber',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='VisitNumber',
        ),
    ]
