# Generated by Django 4.0.5 on 2022-07-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlasmak', '0002_delete_category_delete_certificate_delete_daynumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('number', models.CharField(max_length=225)),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlasmak.catalog')),
            ],
            options={
                'verbose_name': 'Техническая характеристика',
                'verbose_name_plural': 'Технические характеристики',
                'ordering': ['title'],
            },
        ),
    ]
