# Generated by Django 4.0.4 on 2022-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlasmak', '0002_delete_category_delete_certificate_delete_daynumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
