# Generated by Django 4.0.4 on 2022-07-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlasmak', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Контакты'},
        ),
    ]
