# Generated by Django 4.0.5 on 2022-07-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlasmak', '0003_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='specifications',
        ),
    ]
